### ISSUE TITLE
червоний значок "рішення прийнято"

### ISSUE THREAD

**Issue by lisoffsky** [OPORA/publicwhip-kharkiv#1]
по всім рішенням значок того, що вони прийняті - червоний. 
ось [як тут](https://kharkiv.rada4you.org/divisions/2016-10-26/66), наприклад.

![image](https://user-images.githubusercontent.com/14181306/28569457-85a4c140-7142-11e7-93bf-e1aec17c9451.png)

**Comment by beastie87** [comment]
Fix Done!
